/* CAMPUSKLASSE – LERNMETHODEN */
export async function renderLernmethoden(){
  const c=window.CampusFirebase;
  if(!c) throw new Error("CampusFirebase ist noch nicht bereit.");
  const methods=[
    ["🧭","Lernen planen","Wenn du vor einer Aufgabe oder Prüfung stehst und deinen Lernweg klären möchtest.",["Was soll ich am Ende können?","Was kann ich schon?","Welche Schritte brauche ich?","Was ist mein nächster konkreter Schritt?"],["Planung","Ziele","Überblick"]],
    ["🧠","Verstehen statt Auswendiglernen","Wenn du einen Inhalt wirklich verstehen und erklären können möchtest.",["Erkläre den Inhalt mit eigenen Worten.","Formuliere eine Frage dazu.","Finde ein passendes Beispiel.","Erkläre den Zusammenhang anschließend jemand anderem."],["Verstehen","Erklären","Transfer"]],
    ["❓","Fragen entwickeln","Wenn du mit einem Thema arbeitest, aber noch nicht weißt, wo du anfangen sollst.",["Was weiß ich bereits?","Was verstehe ich noch nicht?","Welche Frage möchte ich beantworten?","Welche Informationen brauche ich dafür?"],["Fragen","Recherche","Denken"]],
    ["🗂️","Strukturieren","Wenn viele Informationen vor dir liegen und du den Überblick behalten möchtest.",["Sammle die wichtigsten Informationen.","Ordne sie nach Themen oder Zusammenhängen.","Markiere Schlüsselbegriffe.","Erstelle eine Übersicht, Mindmap oder Tabelle."],["Ordnen","Übersicht","Mindmap"]],
    ["🔁","Aktiv wiederholen","Wenn du Stoff langfristig behalten möchtest.",["Schließe deine Unterlagen.","Rufe die wichtigsten Punkte aus dem Gedächtnis ab.","Kontrolliere deine Antwort.","Wiederhole gezielt Unsicherheiten."],["Wiederholen","Abrufen","Gedächtnis"]],
    ["🗣️","Lernen durch Erklären","Wenn du prüfen möchtest, ob du einen Inhalt wirklich verstanden hast.",["Erkläre das Thema ohne Unterlagen.","Verwende einfache Sprache.","Finde ein Beispiel.","Notiere Stellen, an denen du ins Stocken gerätst."],["Erklären","Verstehen","Selbstcheck"]],
    ["👥","Gemeinsam lernen","Wenn du vom Austausch und unterschiedlichen Perspektiven profitieren möchtest.",["Gemeinsames Lernziel formulieren.","Einen Teil erklären.","Gegenseitig Fragen stellen.","Wichtigste Erkenntnisse festhalten."],["Team","Austausch","Perspektiven"]],
    ["🎯","Prüfung vorbereiten","Wenn eine Kurzarbeit, Schulaufgabe oder Prüfung bevorsteht.",["Relevante Themen sammeln.","Sicher und unsicher unterscheiden.","Unsicherheiten gezielt bearbeiten.","Ohne Unterlagen testen."],["Prüfung","Lernstand","Prioritäten"]],
    ["🔍","Recherche","Wenn du Informationen selbstständig finden, prüfen und nutzen möchtest.",["Recherchefrage formulieren.","Mehrere geeignete Quellen suchen.","Autor, Aktualität und Herkunft prüfen.","Aussagen vergleichen."],["Recherche","Quellen","Bewerten"]],
    ["🤖","KI als Lernpartner","Wenn du KI nutzen möchtest, ohne das eigene Denken abzugeben.",["Eigene Frage oder Idee formulieren.","KI erklären oder Fragen stellen lassen.","Antwort kritisch prüfen.","Ergebnis anschließend selbst formulieren."],["KI","Feedback","Eigenleistung"]],
    ["🪜","In kleinen Schritten lernen","Wenn eine Aufgabe zu groß oder unübersichtlich wirkt.",["Endziel formulieren.","In Teilaufgaben teilen.","Nur den nächsten Schritt bearbeiten.","Ergebnis kurz prüfen."],["Schritte","Fokus","Motivation"]],
    ["💬","Feedback nutzen","Wenn du aus einer Rückmeldung gezielt weiterlernen möchtest.",["Was ist gelungen?","Was soll verbessert werden?","Was genau muss ich verändern?","Was probiere ich beim nächsten Mal anders?"],["Feedback","Verbessern","Reflexion"]]
  ];
  return `${c.pageHead("LERNWERKSTATT","Lernmethoden","Finde eine Methode, die zu deinem aktuellen Lernanliegen passt.",`<a class="secondary" href="#lernwerkstatt">← Lernwerkstatt</a>`)}
  <div class="card"><h2>Was möchtest du gerade erreichen?</h2><p>Wähle eine Methode passend zu deinem nächsten Lernschritt. Du musst nicht die „beste“ Methode kennen – probiere eine aus und prüfe danach, ob sie dir hilft.</p>
  <div class="chips" style="margin-top:12px"><span class="chip">🎯 Planen</span><span class="chip">🧠 Verstehen</span><span class="chip">🔁 Behalten</span><span class="chip">🤝 Gemeinsam lernen</span><span class="chip">🤖 KI nutzen</span></div></div>
  <div class="grid grid-2" style="margin-top:12px">${methods.map(m=>`<article class="card method-card"><div class="method-head"><span class="emoji">${m[0]}</span><div><h2>${m[1]}</h2><p>${m[2]}</p></div></div><h3>So kannst du vorgehen</h3><ol class="method-steps">${m[3].map(x=>`<li>${x}</li>`).join("")}</ol><div class="chips">${m[4].map(x=>`<span class="chip">${x}</span>`).join("")}</div></article>`).join("")}</div>
  <div class="card" style="margin-top:12px"><h3>💡 Danach</h3><p>Wähle eine Methode, probiere sie aus und prüfe anschließend deinen Lernstand oder reflektiere deinen Lernprozess.</p><div class="actions"><a class="primary" href="#lernpfad">🧭 Lernpfad</a><a class="secondary" href="#lernstand">📊 Lernstandsmessung</a><a class="secondary" href="#journal">📓 Lernjournal</a></div></div>${c.footer()}`;
}
